# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/kdemertzis/Earthquakes/blob/main/GRADIO-Classification_ROW_FORM_BARE.ipynb
"""

"""
    Import library
"""
##-- PyCaret
import pycaret
from pycaret.classification import *
##-- Pandas
import pandas as pd
from pandas import Series, DataFrame

url = 'https://raw.githubusercontent.com/kdemertzis/Earthquakes/main/Data/Gradio/1_3class.csv'
# load the dataset
df = pd.read_csv(url)

# setup the dataset
grid = setup(data=df, target=df.columns[-1], html=False, silent=True, verbose=False)

best = compare_models(cross_validation=True, n_select = 10, turbo=True) 
compare_model_results = pull()

lightgbm = create_model('lightgbm')

dashboard(lightgbm)